In [ ]:
!pip install kagglehub

Requirement already satisfied: kagglehub in /usr/local/lib/python3.12/dist-packages (0.3.13)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kagglehub) (26.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kagglehub) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kagglehub) (4.67.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2026.1.4)

In [ ]:
import kagglehub

path = kagglehub.dataset_download("orvile/english-to-turkish-sentence-pairs") #https://www.kaggle.com/datasets/orvile/english-to-turkish-sentence-pairs/data

print("Path to dataset files:", path)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Downloading from https://www.kaggle.com/api/v1/datasets/download/orvile/english-to-turkish-sentence-pairs?dataset_version_number=1...

100%|██████████| 22.0M/22.0M [00:02<00:00, 9.56MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/orvile/english-to-turkish-sentence-pairs/versions/1

In [ ]:
import pandas as pd
import os

print(os.listdir(path))  # see available files


file_path = path + "/Sentence pairs in English-Turkish - 2025-05-06.tsv"

df = pd.read_csv(file_path, sep="\t", engine="python", on_bad_lines="skip")

df.head()

['Sentence pairs in English-Turkish - 2025-05-06.tsv']

,1276,Let's try something.,477649,Bir şeyler deneyelim!
0,1277,I have to go to sleep.,1166752,Yatmaya gitmek zorundayım.
1,1277,I have to go to sleep.,1283434,Uyumam lazım.
2,1280,Today is June 18th and it is Muiriel's birthday!,1090572,Bugün 18 Haziran ve Muiriel'in doğum günü!
3,1282,Muiriel is 20 now.,475258,Muiriel şimdi 20 yaşında.
4,1282,Muiriel is 20 now.,1090575,Muiriel şimdi 20.

In [ ]:
pronouns = [" I ", " You ", " He ", " She ", " They ", " We "]

df = df[df["Let's try something."].str.contains("|".join(pronouns))]

In [ ]:
len(df)

38103

In [ ]:
df["word_count"] = df["Let's try something."].str.split().str.len()

df = df[df["word_count"] >= 4]

In [ ]:
len(df)

37986

In [ ]:
!pip install spacy
!python -m spacy download en_core_web_sm

Requirement already satisfied: spacy in /usr/local/lib/python3.12/dist-packages (3.8.11)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (8.3.10)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.4.3)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.23.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.32.4)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (26.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.1.4)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.3)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: typer>=0.23.1 in /usr/local/lib/python3.12/dist-packages (from typer-slim<1.0.0,>=0.3.0->spacy) (0.23.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.4.2->spacy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.4.2->spacy) (7.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.4.2->spacy) (2.1.1)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.23.1->typer-slim<1.0.0,>=0.3.0->spacy) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.23.1->typer-slim<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.23.1->typer-slim<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.23.1->typer-slim<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->typer>=0.23.1->typer-slim<1.0.0,>=0.3.0->spacy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->typer>=0.23.1->typer-slim<1.0.0,>=0.3.0->spacy) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer>=0.23.1->typer-slim<1.0.0,>=0.3.0->spacy) (0.1.2)
Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 70.6 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [ ]:
import spacy

nlp = spacy.load("en_core_web_sm")

keywords = ["but", "though", "yet", "while", "whereas", "however", "although", "since", "if","unless", "before", "after", "when", "once", ";"]
clause_deps = ["ccomp", "xcomp", "advcl", "acl", "relcl"]

filtered_sentences = []

for sentence in df["Let's try something."]:
    doc = nlp(sentence)

    has_keyword = any(token.text.lower() in keywords for token in doc)
    has_clause = any(token.dep_ in clause_deps for token in doc)

    # OR condition
    if has_keyword or has_clause:
        filtered_sentences.append(sentence)

print("Filtered sentence count:", len(filtered_sentences))

Filtered sentence count: 28694

In [ ]:
df.head(20)

,1276,Let's try something.,477649,Bir şeyler deneyelim!,word_count
15,1292,I don't know if I have the time.,1090626,Zamanım olup olmadığını bilmiyorum.,8
17,1295,You're in better shape than I am.,1090630,Siz benden daha çok formdasınız.,7
28,1309,I'll call them tomorrow when I come back.,1522115,Yarın geri döndüğümde onları arayacağım.,8
29,1309,I'll call them tomorrow when I come back.,2581164,Geri döndüğümde onları yarın ararım.,8
39,1318,The last person I told my idea to thought I wa...,2581159,Fikrimi söylediğim son kişi deli olduğumu düşü...,12
40,1319,"If the world weren't in the shape it is now, I...",1117336,"Dünya şimdi olduğu durumda olmasa, kimseye güv...",14
41,1319,"If the world weren't in the shape it is now, I...",3007235,Eğer dünya şimdiki şeklinde olmasaydı herhangi...,14
54,1332,For some reason I feel more alive at night.,1117367,Bazı sebeplerden dolayı geceleri daha canlı hi...,9
61,1337,"When I grow up, I want to be a king.",2736196,Büyüyünce bir kral olmak istiyorum.,10
78,1355,"I may be antisocial, but it doesn't mean I don...",2438201,"Asosyal olabilirim , ama bu insanlarla konuşma...",13
79,1355,"I may be antisocial, but it doesn't mean I don...",2581218,Antisosyal olabilirim fakat bu insanlarla konu...,13
81,1359,"I'd be unhappy, but I wouldn't kill myself.",526326,Mutsuz olurdum ama kendimi öldürmezdim.,8
82,1360,"Back in high school, I got up at 6 a.m. every ...",2581197,"Geçmişte lisede, her sabah altıda kalkardım.",12
83,1361,"When I woke up, I was sad.",633968,Uyandığımda üzgündüm.,7
84,1365,"If I could send you a marshmallow, Trang, I wo...",780714,"Eğer sana marshmallow gönderebilseydim, Trang,...",10
88,1372,"Whenever I find something I like, it's too exp...",2306982,"Ne zaman hoşuma giden bir şey bulsam, hep paha...",9
93,1382,If anyone was to ask what the point of the sto...,2899780,"Eğer biri bu kitabın konusu ne diye sorarsa, g...",16
102,1392,My physics teacher doesn't care if I skip clas...,2581187,Derslere gitmezsem fizik öğretmenim umursamaz.,9
103,1393,I wish I could go to Japan.,1306553,Keşke Japonya'ya gidebilsem.,7
108,1396,"After that, I left, but then I realized that I...",3563616,"Ondan sonra, ayrıldım ama onların evinde çanta...",16

In [ ]:
import spacy

nlp = spacy.load("en_core_web_sm")

col = "Let's try something."

keywords = ["but", "though", "yet", "while", "whereas", "however",
            "although", "since", "if", "unless", "before",
            "after", "when", "once", ";"]

clause_deps = ["ccomp", "xcomp", "advcl", "acl", "relcl"]

filtered_rows = []

for idx, sentence in df[col].items():

    if not isinstance(sentence, str):
        continue

    # Remove questions
    if sentence.strip().endswith("?"):
        continue

    doc = nlp(sentence)

    has_keyword = any(token.text.lower() in keywords for token in doc)
    has_clause = any(token.dep_ in clause_deps for token in doc)

    if has_keyword or has_clause:
        filtered_rows.append(df.loc[idx])

filtered_df = pd.DataFrame(filtered_rows)

print("Final filtered size:", len(filtered_df))

Final filtered size: 25465

In [ ]:
filtered_df.to_csv("data.csv", index=False)